# Generated by Django 6.1.1 on 2026-09-14 20:24

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_oportunidade_orcamento_venda_visitatecnica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('modulo', 'Módulo fotovoltaico'), ('inversor', 'Inversor'), ('estrutura', 'Estrutura'), ('protecao', 'Proteção elétrica'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('potencia_nominal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade', models.CharField(default='unidade', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('categoria', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=core.models.gerar_codigo_projeto, max_length=18, unique=True)),
                ('nome', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('dimensionamento', 'Dimensionamento'), ('aprovado', 'Aprovado'), ('em_instalacao', 'Em instalação'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='planejamento', max_length=20)),
                ('endereco_instalacao', models.CharField(blank=True, max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='core.cliente')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='core.oportunidade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('art', 'ART / RRT'), ('diagrama', 'Diagrama elétrico'), ('planta', 'Planta de instalação'), ('memorial', 'Memorial descritivo'), ('manual', 'Manual de equipamento'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='documentacao_tecnica/')),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tecnicos', to='core.projeto')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Dimensionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_medio_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irradiacao_media', models.DecimalField(decimal_places=2, default=0, help_text='kWh/m²/dia', max_digits=6)),
                ('fator_performance', models.DecimalField(decimal_places=2, default=0.8, max_digits=5)),
                ('potencia_calculada_kwp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_modulos', models.PositiveIntegerField(default=0)),
                ('potencia_modulo_wp', models.PositiveIntegerField(default=0)),
                ('potencia_inversor_kw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('geracao_estimada_anual_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('area_necessaria_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensionamento', to='core.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('potencia_kwp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_instalacao', 'Em instalação'), ('operacional', 'Operacional'), ('manutencao', 'Em manutenção')], default='planejamento', max_length=20)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('equipamentos', models.ManyToManyField(related_name='sistemas', through='core.SistemaEquipamento', to='core.equipamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_solares', to='core.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='sistemaequipamento',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistemasolar'),
        ),
        migrations.AlterUniqueTogether(
            name='sistemaequipamento',
            unique_together={('sistema', 'equipamento')},
        ),
    ]
