# Generated by Django 6.1.1 on 2026-09-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipamento_projeto_documentotecnico_dimensionamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Solar Gest', max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('moeda', models.CharField(default='BRL', max_length=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da empresa',
                'verbose_name_plural': 'Configurações da empresa',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('portal', 'Portal'), ('outro', 'Outro')], default='whatsapp', max_length=12)),
                ('prioridade', models.CharField(default='normal', max_length=12)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_cliente', 'Aguardando cliente'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='core.sistemasolar')),
            ],
            options={
                'ordering': ('status', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=20)),
                ('rota', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('metodo', models.CharField(default='GET', max_length=10)),
                ('status_http', models.PositiveSmallIntegerField(default=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_calculo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('paga', 'Paga')], default='pendente', max_length=12)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='core.venda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagar', 'Conta a pagar'), ('receber', 'Conta a receber')], max_length=10)),
                ('descricao', models.CharField(max_length=180)),
                ('categoria', models.CharField(default='Geral', max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_financeiras', to='core.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_financeiras_criadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_financeiras', to='core.projeto')),
            ],
            options={
                'ordering': ('vencimento', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('acionada', 'Acionada'), ('encerrada', 'Encerrada')], default='ativa', max_length=12)),
                ('termos', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, upload_to='garantias/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='core.equipamento')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='core.sistemasolar')),
            ],
            options={
                'ordering': ('fim', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='HistoricoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('instalado', 'Instalado'), ('substituido', 'Substituído'), ('manutencao', 'Manutenção'), ('removido', 'Removido')], max_length=15)),
                ('data_evento', models.DateField()),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='core.equipamento')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_equipamentos', to='core.sistemasolar')),
            ],
            options={
                'ordering': ('-data_evento', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], default='corretiva', max_length=12)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('agendada', 'Agendada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=15)),
                ('prioridade', models.CharField(default='normal', max_length=12)),
                ('data_agendada', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.sistemasolar')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'data_agendada', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('lido', 'Lido'), ('resolvido', 'Resolvido')], default='aberto', max_length=12)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.sistemasolar')),
                ('manutencao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.manutencao')),
            ],
            options={
                'ordering': ('status', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('descricao', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_movimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_caixa', to='core.contafinanceira')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_movimento', '-criado_em'),
            },
        ),
    ]
