TRANSLATIONS = {
    'pt-br': {
        'operation': 'Operação', 'dashboard': 'Dashboard', 'commercial': 'Comercial', 'leads': 'Leads',
        'clients': 'Clientes', 'engineering': 'Engenharia', 'finance': 'Financeiro', 'management': 'Gestão',
        'plants': 'Usinas', 'team': 'Equipe', 'reports': 'Relatórios', 'language': 'Idioma', 'logout': 'Sair',
        'active_users': 'Usuários ativos', 'solar_systems': 'Sistemas solares', 'new_system': 'Novo sistema',
        'no_plants': 'Nenhuma usina cadastrada.', 'no_users': 'Nenhum usuário ativo.', 'user_management': 'Gestão de usuários',
        'solar_operation': 'Sistemas solares instalados e em acompanhamento.', 'team_description': 'Usuários e responsáveis pela operação do Solar Gest.',
        'records': 'Registros', 'name': 'Nome', 'contact': 'Contato', 'origin': 'Origem', 'status': 'Status', 'owner': 'Responsável',
        'opportunity': 'Oportunidade', 'stage': 'Etapa', 'estimated_value': 'Valor estimado', 'probability': 'Probabilidade',
        'date': 'Data', 'time': 'Horário', 'address': 'Endereço', 'code': 'Código', 'description': 'Descrição', 'value': 'Valor',
        'category': 'Categoria', 'customer_supplier': 'Cliente / fornecedor', 'due_date': 'Vencimento', 'seller': 'Vendedor',
        'sale': 'Venda', 'percentage': 'Percentual', 'base': 'Base', 'version': 'Versão', 'file': 'Arquivo',
        'new_lead': 'Novo lead', 'new_opportunity': 'Nova oportunidade', 'new_visit': 'Agendar visita', 'new_quote': 'Novo orçamento',
        'new_sale': 'Registrar venda', 'new_record': 'Novo registro', 'none_leads': 'Nenhum lead cadastrado.',
        'none_opportunities': 'Nenhuma oportunidade cadastrada.', 'none_visits': 'Nenhuma visita agendada.',
        'none_quotes': 'Nenhum orçamento cadastrado.', 'none_sales': 'Nenhuma venda registrada.', 'none_accounts': 'Nenhuma conta cadastrada.',
        'select': 'Selecione', 'save': 'Salvar registro', 'cancel': 'Cancelar', 'observations': 'Observações', 'projects': 'Projetos', 'none_projects': 'Nenhum projeto cadastrado.', 'commercial_area': 'Comercial', 'leads_title': 'Leads', 'leads_description': 'Potenciais clientes e novos contatos.', 'crm_title': 'CRM', 'crm_description': 'Acompanhe oportunidades ao longo do funil de vendas.', 'visits_title': 'Visitas técnicas', 'visits_description': 'Organize vistorias e levantamentos no local.', 'quotes_title': 'Orçamentos', 'quotes_description': 'Crie e acompanhe propostas para seus clientes.', 'sales_title': 'Vendas', 'sales_description': 'Negócios fechados e em implantação.',
    },
    'en': {
        'operation': 'Operations', 'dashboard': 'Dashboard', 'commercial': 'Sales', 'leads': 'Leads',
        'clients': 'Clients', 'engineering': 'Engineering', 'finance': 'Finance', 'management': 'Management',
        'plants': 'Plants', 'team': 'Team', 'reports': 'Reports', 'language': 'Language', 'logout': 'Sign out',
        'active_users': 'Active users', 'solar_systems': 'Solar systems', 'new_system': 'New system',
        'no_plants': 'No plants registered.', 'no_users': 'No active users.', 'user_management': 'User management',
        'solar_operation': 'Installed solar systems under monitoring.', 'team_description': 'Users and people responsible for Solar Gest operations.',
        'records': 'Records', 'name': 'Name', 'contact': 'Contact', 'origin': 'Source', 'status': 'Status', 'owner': 'Owner',
        'opportunity': 'Opportunity', 'stage': 'Stage', 'estimated_value': 'Estimated value', 'probability': 'Probability',
        'date': 'Date', 'time': 'Time', 'address': 'Address', 'code': 'Code', 'description': 'Description', 'value': 'Value',
        'category': 'Category', 'customer_supplier': 'Customer / supplier', 'due_date': 'Due date', 'seller': 'Salesperson',
        'sale': 'Sale', 'percentage': 'Percentage', 'base': 'Base', 'version': 'Version', 'file': 'File',
        'new_lead': 'New lead', 'new_opportunity': 'New opportunity', 'new_visit': 'Schedule visit', 'new_quote': 'New quote',
        'new_sale': 'Register sale', 'new_record': 'New record', 'none_leads': 'No leads registered.',
        'none_opportunities': 'No opportunities registered.', 'none_visits': 'No visits scheduled.',
        'none_quotes': 'No quotes registered.', 'none_sales': 'No sales registered.', 'none_accounts': 'No accounts registered.',
        'select': 'Select', 'save': 'Save record', 'cancel': 'Cancel', 'observations': 'Notes', 'projects': 'Projects', 'none_projects': 'No projects registered.', 'commercial_area': 'Sales', 'leads_title': 'Leads', 'leads_description': 'Potential customers and new contacts.', 'crm_title': 'CRM', 'crm_description': 'Track opportunities through the sales funnel.', 'visits_title': 'Technical visits', 'visits_description': 'Organize site surveys and inspections.', 'quotes_title': 'Quotes', 'quotes_description': 'Create and track customer proposals.', 'sales_title': 'Sales', 'sales_description': 'Closed and active deals.',
    },
    'es': {
        'operation': 'Operación', 'dashboard': 'Panel', 'commercial': 'Comercial', 'leads': 'Leads',
        'clients': 'Clientes', 'engineering': 'Ingeniería', 'finance': 'Finanzas', 'management': 'Gestión',
        'plants': 'Plantas', 'team': 'Equipo', 'reports': 'Informes', 'language': 'Idioma', 'logout': 'Salir',
        'active_users': 'Usuarios activos', 'solar_systems': 'Sistemas solares', 'new_system': 'Nuevo sistema',
        'no_plants': 'Ninguna planta registrada.', 'no_users': 'Ningún usuario activo.', 'user_management': 'Gestión de usuarios',
        'solar_operation': 'Sistemas solares instalados y en seguimiento.', 'team_description': 'Usuarios y responsables de la operación de Solar Gest.',
        'records': 'Registros', 'name': 'Nombre', 'contact': 'Contacto', 'origin': 'Origen', 'status': 'Estado', 'owner': 'Responsable',
        'opportunity': 'Oportunidad', 'stage': 'Etapa', 'estimated_value': 'Valor estimado', 'probability': 'Probabilidad',
        'date': 'Fecha', 'time': 'Hora', 'address': 'Dirección', 'code': 'Código', 'description': 'Descripción', 'value': 'Valor',
        'category': 'Categoría', 'customer_supplier': 'Cliente / proveedor', 'due_date': 'Vencimiento', 'seller': 'Vendedor',
        'sale': 'Venta', 'percentage': 'Porcentaje', 'base': 'Base', 'version': 'Versión', 'file': 'Archivo',
        'new_lead': 'Nuevo lead', 'new_opportunity': 'Nueva oportunidad', 'new_visit': 'Agendar visita', 'new_quote': 'Nuevo presupuesto',
        'new_sale': 'Registrar venta', 'new_record': 'Nuevo registro', 'none_leads': 'No hay leads registrados.',
        'none_opportunities': 'No hay oportunidades registradas.', 'none_visits': 'No hay visitas agendadas.',
        'none_quotes': 'No hay presupuestos registrados.', 'none_sales': 'No hay ventas registradas.', 'none_accounts': 'No hay cuentas registradas.',
        'select': 'Seleccione', 'save': 'Guardar registro', 'cancel': 'Cancelar', 'observations': 'Observaciones', 'projects': 'Proyectos', 'none_projects': 'No hay proyectos registrados.', 'commercial_area': 'Comercial', 'leads_title': 'Leads', 'leads_description': 'Potenciales clientes y nuevos contactos.', 'crm_title': 'CRM', 'crm_description': 'Sigue las oportunidades del embudo de ventas.', 'visits_title': 'Visitas técnicas', 'visits_description': 'Organiza visitas y levantamientos en el sitio.', 'quotes_title': 'Presupuestos', 'quotes_description': 'Crea y sigue propuestas para tus clientes.', 'sales_title': 'Ventas', 'sales_description': 'Negocios cerrados y en implementación.',
    },
    'it': {
        'operation': 'Operazioni', 'dashboard': 'Dashboard', 'commercial': 'Commerciale', 'leads': 'Lead',
        'clients': 'Clienti', 'engineering': 'Ingegneria', 'finance': 'Finanza', 'management': 'Gestione',
        'plants': 'Impianti', 'team': 'Squadra', 'reports': 'Rapporti', 'language': 'Lingua', 'logout': 'Esci',
        'active_users': 'Utenti attivi', 'solar_systems': 'Impianti solari', 'new_system': 'Nuovo impianto',
        'no_plants': 'Nessun impianto registrato.', 'no_users': 'Nessun utente attivo.', 'user_management': 'Gestione utenti',
        'solar_operation': 'Impianti solari installati e monitorati.', 'team_description': 'Utenti e responsabili delle operazioni Solar Gest.',
        'records': 'Registri', 'name': 'Nome', 'contact': 'Contatto', 'origin': 'Origine', 'status': 'Stato', 'owner': 'Responsabile',
        'opportunity': 'Opportunità', 'stage': 'Fase', 'estimated_value': 'Valore stimato', 'probability': 'Probabilità',
        'date': 'Data', 'time': 'Ora', 'address': 'Indirizzo', 'code': 'Codice', 'description': 'Descrizione', 'value': 'Valore',
        'category': 'Categoria', 'customer_supplier': 'Cliente / fornitore', 'due_date': 'Scadenza', 'seller': 'Venditore',
        'sale': 'Vendita', 'percentage': 'Percentuale', 'base': 'Base', 'version': 'Versione', 'file': 'File',
        'new_lead': 'Nuovo lead', 'new_opportunity': 'Nuova opportunità', 'new_visit': 'Pianifica visita', 'new_quote': 'Nuovo preventivo',
        'new_sale': 'Registra vendita', 'new_record': 'Nuovo registro', 'none_leads': 'Nessun lead registrato.',
        'none_opportunities': 'Nessuna opportunità registrata.', 'none_visits': 'Nessuna visita programmata.',
        'none_quotes': 'Nessun preventivo registrato.', 'none_sales': 'Nessuna vendita registrata.', 'none_accounts': 'Nessun conto registrato.',
        'select': 'Seleziona', 'save': 'Salva registro', 'cancel': 'Annulla', 'observations': 'Note', 'projects': 'Progetti', 'none_projects': 'Nessun progetto registrato.', 'commercial_area': 'Commerciale', 'leads_title': 'Lead', 'leads_description': 'Potenziali clienti e nuovi contatti.', 'crm_title': 'CRM', 'crm_description': 'Segui le opportunità nel processo di vendita.', 'visits_title': 'Visite tecniche', 'visits_description': 'Organizza sopralluoghi e rilievi.', 'quotes_title': 'Preventivi', 'quotes_description': 'Crea e segui le proposte per i clienti.', 'sales_title': 'Vendite', 'sales_description': 'Affari chiusi e in implementazione.',
    },
    'sq': {
        'operation': 'Operacioni', 'dashboard': 'Paneli', 'commercial': 'Shitje', 'leads': 'Kontakte',
        'clients': 'Klientë', 'engineering': 'Inxhinieri', 'finance': 'Financa', 'management': 'Menaxhim',
        'plants': 'Centralet', 'team': 'Ekipi', 'reports': 'Raporte', 'language': 'Gjuha', 'logout': 'Dilni',
        'active_users': 'Përdorues aktivë', 'solar_systems': 'Sisteme diellore', 'new_system': 'Sistem i ri',
        'no_plants': 'Nuk ka centrale të regjistruara.', 'no_users': 'Nuk ka përdorues aktivë.', 'user_management': 'Menaxhimi i përdoruesve',
        'solar_operation': 'Sisteme diellore të instaluara dhe në monitorim.', 'team_description': 'Përdoruesit dhe përgjegjësit e operacioneve Solar Gest.',
        'records': 'Regjistrime', 'name': 'Emri', 'contact': 'Kontakt', 'origin': 'Burimi', 'status': 'Statusi', 'owner': 'Përgjegjësi',
        'opportunity': 'Mundësi', 'stage': 'Faza', 'estimated_value': 'Vlera e parashikuar', 'probability': 'Probabiliteti',
        'date': 'Data', 'time': 'Ora', 'address': 'Adresa', 'code': 'Kodi', 'description': 'Përshkrimi', 'value': 'Vlera',
        'category': 'Kategoria', 'customer_supplier': 'Klient / furnizues', 'due_date': 'Afati', 'seller': 'Shitësi',
        'sale': 'Shitja', 'percentage': 'Përqindja', 'base': 'Baza', 'version': 'Versioni', 'file': 'Skedari',
        'new_lead': 'Kontakt i ri', 'new_opportunity': 'Mundësi e re', 'new_visit': 'Planifiko vizitë', 'new_quote': 'Preventiv i ri',
        'new_sale': 'Regjistro shitje', 'new_record': 'Regjistrim i ri', 'none_leads': 'Nuk ka kontakte të regjistruara.',
        'none_opportunities': 'Nuk ka mundësi të regjistruara.', 'none_visits': 'Nuk ka vizita të planifikuara.',
        'none_quotes': 'Nuk ka preventivë të regjistruar.', 'none_sales': 'Nuk ka shitje të regjistruara.', 'none_accounts': 'Nuk ka llogari të regjistruara.',
        'select': 'Zgjidhni', 'save': 'Ruaj regjistrimin', 'cancel': 'Anulo', 'observations': 'Shënime', 'projects': 'Projekte', 'none_projects': 'Nuk ka projekte të regjistruara.', 'commercial_area': 'Shitje', 'leads_title': 'Kontakte', 'leads_description': 'Klientë të mundshëm dhe kontakte të reja.', 'crm_title': 'CRM', 'crm_description': 'Ndiqni mundësitë në procesin e shitjes.', 'visits_title': 'Vizita teknike', 'visits_description': 'Organizoni inspektimet në terren.', 'quotes_title': 'Preventivë', 'quotes_description': 'Krijoni dhe ndiqni ofertat për klientët.', 'sales_title': 'Shitje', 'sales_description': 'Marrëveshje të mbyllura dhe aktive.',
    },
}


def ui(request):
    language = getattr(request, 'LANGUAGE_CODE', 'pt-br')
    return {'ui': TRANSLATIONS.get(language, TRANSLATIONS['pt-br'])}
